1st homework
daniildiveev/mts-recsys pull request #1
Opened 2022-12-10 20:25 UTC by daniildiveev

Привет, не понял как сделать предсказание только на юзер фичах: при создании датасета просит еще и фичи айтемов

2022-12-12 07:41 UTC, sharthZ23 requested changes
- Зачем свои модели реализованы, если в ipynb используешь `rectools`?
- Залитый jupyter содержит excеption
- Мало визуализации и описаний
- Нет результатов моделей на лидерборде 
- Нет сравнения метрик по оффлайн валидации и метрики на лидерборде

2022-12-12 07:41 UTC, sharthZ23 commented on models/popular_among_n_unique.py
> +class PopularAmongNUniqueUsers(PopularModel):
Классу не хватает метода recommend. Лучше делать так, чтобы у разных моделей сигнатура общая совпадала на уровне fit/predict

2022-12-14 19:19 UTC, daniildiveev commented on models/popular_among_n_unique.py
> +class PopularAmongNUniqueUsers(PopularModel):
- ![image](https://user-images.githubusercontent.com/69817199/207691207-51b55ec0-793d-488b-afd7-4b28e68b1f02.png)
 - пофиксил
- не совсем понимаю что здесь можно визуализировать
- пофиксил
- не совсем понимаю как сравнивать, у меня с лидерборда идет один скор всего лишь, или надо было сабмитить много моделей одного типа?

2022-12-14 19:52 UTC, daniildiveev commented
- ![image](https://user-images.githubusercontent.com/69817199/207700450-ad206b4c-05e2-41f3-82d7-41003baaf88e.png)
- пофиксил
- не совсем понимаю что здесь можно визуализировать
- пофиксил
- не совсем понимаю как сравнивать, у меня с лидерборда идет один скор всего лишь, или надо было сабмитить много моделей одного типа?

2022-12-16 19:31 UTC, sharthZ23 approved these changes
Принято, 8 баллов

2022-12-16 19:47 UTC, merged